const SinavListesi = [
  {
    name: "Matematik 1",
    code: "MAT-101",
    started: false,
    finished: false,
    kisiId: null,
    result: null,
    sorular: [
      "1) 3x + 5 = 20 denklemini sağlayan x değeri nedir?",
      "2) 2(x - 3) = 10 denklemini sağlayan x değeri nedir?",
      "3) 4x - 7 = 13 denklemini sağlayan x değeri nedir?",
      "4) x^2 - 4 = 0 denklemini sağlayan x değeri nedir?",
      "5) 5(x + 2) = 3x + 14 denklemini sağlayan x değeri nedir?",
      "6) 2x + 3 = 7x - 12 denklemini sağlayan x değeri nedir?",
      "7) x / 3 + 5 = 8 denklemini sağlayan x değeri nedir?",
      "8) 3x - 2 = 2x + 5 denklemini sağlayan x değeri nedir?",
      "9) 4(x + 3) = 2x + 18 denklemini sağlayan x değeri nedir?",
      "10) x^2 - 9 = 0 denklemini sağlayan x değeri nedir?",
    ],
    cevaplar: [
      ["A) 3", "B) 4", "C) 5", "D) 6"],
      ["A) 5", "B) 6", "C) 7", "D) 8"],
      ["A) 3", "B) 4", "C) 5", "D) 6"],
      ["A) 1", "B) 2", "C) -2", "D) Hem B hem C"],
      ["A) 1", "B) 2", "C) 3", "D) 4"],
      ["A) 1", "B) 2", "C) 3", "D) 4"],
      ["A) 6", "B) 7", "C) 8", "D) 9"],
      ["A) 5", "B) 6", "C) 7", "D) 8"],
      ["A) 2", "B) 3", "C) 4", "D) 5"],
      ["A) 3", "B) -3", "C) Hem A hem B", "D) 0"],
    ],
    dogruCevap: ["B", "C", "C", "D", "B", "C", "D", "A", "B", "C"],
  },
  {
    name: "Fizik 1",
    code: "FIZ-103",
    started: false,
    finished: false,
    kisiId: null,
    result: null,
    sorular: [
      '1) Newton\'un üçüncü yasası aşağıdakilerden hangisidir?',
      '2) Bir cisim 5 m/s hızla hareket ederken 2 m/s^2 ivme ile duruncaya kadar ne kadar süre geçer?',
      '3) 10 N kuvveti ile 2 m/s^2 ivme kazanan bir cismin kütlesi nedir?',
      '4) Bir cisim 50 J enerjiye sahiptir. Eğer 5 saniye boyunca 10 W güç harcarsa, kalan enerjisi ne olur?',
      '5) Duran bir cisim, 4 m/s^2 ivme ile 3 saniye boyunca ivmelenirse, son hızı ne olur?',
      '6) Kütlesi 3 kg olan bir cisim, 4 m/s^2 ivme ile hareket ederse, üzerine etki eden kuvvet nedir?',
      '7) 60 kg kütleli bir kişi, 10 m/s^2 ivme ile serbest düşerse, yere çarptığında yere uyguladığı kuvvet nedir?',
      '8) Bir cisim 5 m yükseklikten serbest bırakılırsa, yere çarptığında sahip olacağı hız nedir? (g = 10 m/s^2)',
      '9) Kütlesi 4 kg olan bir cisim, 5 m/s^2 ivme ile 10 saniye boyunca hareket ederse, aldığı yol nedir?',
      '10) 100 J enerjiye sahip bir cisim, 10 N kuvvetle 5 metre hareket ettirilirse, yapılan iş nedir?',
    ],
    cevaplar: [
      ["A) Etki-tepki yasası", "B) Eylemsizlik yasası", "C) Enerji korunumu yasası", "D) İvme yasası"],
      ["A) 1 saniye", "B) 2.5 saniye", "C) 3 saniye", "D) 5 saniye"],
      ["A) 2 kg", "B) 3 kg", "C) 4 kg", "D) 5 kg"],
      ["A) 0 J", "B) 10 J", "C) 20 J", "D) 40 J"],
      ["A) 3 m/s", "B) 4 m/s", "C) 8 m/s", "D) 12 m/s"],
      ["A) 7 N", "B) 10 N", "C) 12 N", "D) 15 N"],
      ["A) 300 N", "B) 600 N", "C) 900 N", "D) 1200 N"],
      ["A) 5 m/s", "B) 7 m/s", "C) 10 m/s", "D) 20 m/s"],
      ["A) 100 m", "B) 200 m", "C) 250 m", "D) 300 m"],
      ["A) 50 J", "B) 100 J", "C) 150 J", "D) 200 J"],
    ],
    dogruCevap: ["A", "B", "C", "C", "B", "C", "B", "C", "D", "D"],
  },
  {
    name: "Mesleki Ingilizce 1",
    code: "ENG-101",
    started: false,
    finished: false,
    kisiId: null,
    result: null,
    sorular: [
      '1) Which of the following is the correct translation for "müşteri"?',
      '2) What is the correct English term for "fatura"?',
      '3) What does "deadline" mean in Turkish?',
      '4) How would you say "iş görüşmesi" in English?',
      '5) What is the English equivalent of "özgeçmiş"?',
      '6) Translate "iş teklifi" into English.',
      '7) What is the term for "çalışma saatleri" in English?',
      '8) What does "promotion" mean in Turkish?',
      '9) How would you translate "mali yıl" into English?',
      '10) What is the correct term for "bütçe" in English?',
    ],
    cevaplar: [
      ["A) Customer", "B) Supplier", "C) Employer", "D) Employee"],
      ["A) Receipt", "B) Invoice", "C) Bill", "D) Statement"],
      ["A) Başvuru", "B) Müşteri", "C) Görüşme", "D) Son teslim tarihi"],
      ["A) Job application", "B) Job interview", "C) Job offer", "D) Job description"],
      ["A) Cover letter", "B) Resume", "C) Reference", "D) Job description"],
      ["A) Job interview", "B) Job application", "C) Job offer", "D) Job description"],
      ["A) Work environment", "B) Workload", "C) Working hours", "D) Working conditions"],
      ["A) Maaş", "B) Terfi", "C) İş tanımı", "D) Çalışma saatleri"],
      ["A) Financial statement", "B) Fiscal year", "C) Budget", "D) Revenue"],
      ["A) Expense", "B) Invoice", "C) Revenue", "D) Budget"],
    ],
    dogruCevap: ["A", "B", "D", "B", "B", "C", "C", "B", "B", "D"],
  },

  {
    name: "Web Programlama",
    code: "WEB-101",
    started: false,
    finished: false,
    kisiId: null,
    result: null,
    sorular: [
      '1) HTML neyin kısaltmasıdır?',
      '2) "app.js" adlı harici bir betiğe başvurmanın doğru söz dizimi nedir?',
      '3) Bir belgenin başlığını tanımlamak için hangi HTML elementi kullanılır?',
      '4) CSS neyin kısaltmasıdır?',
      '5) Bir CSS dosyasına yorum eklemek için nasıl bir söz dizimi kullanılır?',
      '6) CSS\'te arka plan rengini değiştirmek için hangi özellik kullanılır?',
      '7) HTML\'de bir bağlantı oluşturmanın doğru söz dizimi nedir?',
      '8) Bir HTML belgesine yorum eklemek için nasıl bir söz dizimi kullanılır?',
      '9) Sırasız bir listeyi tanımlamak için hangi HTML elementi kullanılır?',
      '10) Bir satır sonu eklemek için doğru HTML elementi nedir?',
    ],
    cevaplar: [
      ["A) Hyper Text Markup Language", "B) Home Tool Markup Language", "C) Hyperlinks and Text Markup Language", "D) Home Text Markup Language"],
      ["A) <script name=\"app.js\"></script>", "B) <script href=\"app.js\"></script>", "C) <script ref=\"app.js\"></script>", "D) <script src=\"app.js\"></script>"],
      ["A) <meta>", "B) <head>", "C) <title>", "D) <header>"],
      ["A) Computer Style Sheets", "B) Cascading Style Sheets", "C) Creative Style Sheets", "D) Colorful Style Sheets"],
      ["A) // bu bir yorumdur", "B) # bu bir yorumdur", "C) <!-- bu bir yorumdur -->", "D) /* bu bir yorumdur */"],
      ["A) font-size", "B) color", "C) margin", "D) background-color"],
      ["A) <a link=\"http://example.com\">Link</a>", "B) <a ref=\"http://example.com\">Link</a>", "C) <a name=\"http://example.com\">Link</a>", "D) <a href=\"http://example.com\">Link</a>"],
      ["A) // bu bir yorumdur", "B) /* bu bir yorumdur */", "C) # bu bir yorumdur", "D) <!-- bu bir yorumdur -->"],
      ["A) <ol>", "B) <ul>", "C) <li>", "D) <dl>"],
      ["A) <lb>", "B) <line>", "C) <break>", "D) <br>"],
    ],
    dogruCevap: ["A", "D", "C", "B", "D", "D", "D", "D", "B", "D"],
  },
];

export default SinavListesi;
